### ISSUE TITLE
Add Yasmina research presented at cognomics conference

### ISSUE THREAD

**Issue by yasmina-mekki** [baobablab/brainomicsteam#1]
**Research details**
- Title: Heritability of the language network using resting state fMRI data
- Contact: yasmina.mekki@cea.fr

**Enter a description**
Language is a singularity of the human species. Its complexity suggests that it is supplemented by an innate language capacity. Using the UK Biobank resource, we try to understand how the brain supports natural language by unveiling the genetics factors that might contribute to it.

Neural activity measured during task performance is the standard approach to study the language processing. However, resting-state functional connectivity identified during free task remains a valid option.

Using [1] region of interest, an heritability study on resting state fMRI functional connectivity related to language processing suggest some genetic influence on the phenotype chosen which indicates that the human language brain organization is under relatively strong genetic control, strong enough to consider association studies with genotyping data.
![brain_connectome_p_corr_UKB](https://user-images.githubusercontent.com/21186462/74938308-0df98680-53ee-11ea-80f0-b1e768de5ded.png)

The poster [2] related to this work can be found at https://hal.archives-ouvertes.fr/cea-02289470v1.

[1] Pallier C. et al. “Cortical representation of the constituent structure of sentences”. In: PNAS 108.6 (2011), pp. 2522–2527.
[2] Mekki Y., et al. "Heritability of the language network using resting state fMRI data". COGNOMICS Conference 2019: Bridging Gaps, Sep 2019, Nijmegen, Netherlands. ⟨cea-02289470⟩

**Comment by VincentFrouin** [comment]
Es tu d'accord pour remplacer :

- However, resting-state functional connectivity identified during free task remains a valid option REMPLACE PAR 
-  However, resting-state functional connectivity identified during free task remains a valid alternative to study langage.

Pourrais tu attacher l'image à part stp et aussi avoir une image avec la résolution demandée 450x350  ou 500x400

**Comment by yasmina-mekki** [comment]
Voici le texte avec les nouvelles modifications :

**Research details**
- Title: Heritability of the language network using resting state fMRI data
- Contact: yasmina.mekki@cea.fr

**Enter a description**
Language is a singularity of the human species. Its complexity suggests that it is supplemented by an innate language capacity. Using the UK Biobank resource, we try to understand how the brain supports natural language by unveiling the genetics factors that might contribute to it.

Neural activity measured during task performance is the standard approach to study the language processing. However, resting-state functional connectivity identified during free task remains a valid alternative to study langage.

Using [1] region of interest, an heritability study on resting state fMRI functional connectivity related to language processing suggest some genetic influence on the phenotype chosen which indicates that the human language brain organization is under relatively strong genetic control, strong enough to consider association studies with genotyping data.

The poster [2] related to this work can be found at https://hal.archives-ouvertes.fr/cea-02289470v1.

[1] Pallier C. et al. “Cortical representation of the constituent structure of sentences”. In: PNAS 108.6 (2011), pp. 2522–2527.
[2] Mekki Y., et al. "Heritability of the language network using resting state fMRI data". COGNOMICS Conference 2019: Bridging Gaps, Sep 2019, Nijmegen, Netherlands. ⟨cea-02289470⟩

**Comment by yasmina-mekki** [comment]
Voici l'image avec la bonne résolution :

![UKB_FC_CP](https://user-images.githubusercontent.com/21186462/75029464-60947a80-54a2-11ea-8006-ca632d4055ec.png)

**Comment by VincentFrouin** [comment]
Information integrated in a new story.
The resolution of the images should be better (ROI name cannot be read...)
